# Import all models here to ensure they're registered with SQLAlchemy metadata
# before Alembic or any query runs.
from .base import Base
from .reference import (
    Benefit,
    Certification,
    CertificationProvider,
    City,
    CompanySiteType,
    CompanyType,
    Country,
    Experience,
    Feature,
    Function,
    FunctionSpecialty,
    Industry,
    JobStatus,
    JobType,
    OfficeLocation,
    Skill,
    SkillCategory,
    SocialMediaType,
    State,
)
from .user import User, UserCertification, UserSkill
from .company import (
    Company,
    CompanyBenefit,
    CompanyFunction,
    CompanyIndustry,
    CompanyInvite,
    CompanySite,
    CompanySocial,
    CompanyTechnology,
    Note,
    UserCompanyRole,
)
from .job import JobListing, JobListingCertification, JobListingSkill
from .application import Application, Notification, SavedJob, SavedSearch
from .scraping import ScrapingLog

__all__ = [
    "Base",
    "Benefit",
    "Certification",
    "CertificationProvider",
    "City",
    "CompanySiteType",
    "CompanyType",
    "Country",
    "Experience",
    "Feature",
    "Function",
    "FunctionSpecialty",
    "Industry",
    "JobStatus",
    "JobType",
    "OfficeLocation",
    "Skill",
    "SkillCategory",
    "SocialMediaType",
    "State",
    "User",
    "UserCertification",
    "UserSkill",
    "Company",
    "CompanyBenefit",
    "CompanyFunction",
    "CompanyIndustry",
    "CompanyInvite",
    "CompanySite",
    "CompanySocial",
    "CompanyTechnology",
    "Note",
    "UserCompanyRole",
    "JobListing",
    "JobListingCertification",
    "JobListingSkill",
    "Application",
    "Notification",
    "SavedJob",
    "SavedSearch",
    "ScrapingLog",
]
